### ISSUE TITLE
padding items

### ISSUE THREAD

**Issue by MohamedMahmoud10** [sharmajatin1997/dropdown_model_list#4]
in localzation or when it right to left 
i want to able to make some padding on options itmes 
![image](https://github.com/sharmajatin1997/dropdown_model_list/assets/102865664/371b5e30-fb27-4ced-bf82-4dc245e81d0e)

**Comment by sharmajatin1997** [comment]
@MohamedMahmoud10 Issue Resolved in New Update 

Please Use this for Customize Padding

paddingDropItem: const EdgeInsets.only(left: 20,top: 10,bottom: 10,right: 20),

Thanks

**Comment by MohamedMahmoud10** [comment]
Thank you very much your library is very amazing keep going🚀🦾
