### ISSUE TITLE
drop down with radio selection 

### ISSUE THREAD

**Issue by MohamedMahmoud10** [sharmajatin1997/dropdown_model_list#5]
hello you are doing a very great jop keep it 
we need a new option of drop down 
drop down with radio selection not multi selection 
like that 
![image](https://github.com/sharmajatin1997/dropdown_model_list/assets/102865664/ce9abce0-897c-4d9d-bd42-0e10692768f4)

**Comment by sharmajatin1997** [comment]
@MohamedMahmoud10 Currently am not available but i will update in next version. if you are free please take fork and Update and Create Pull Request otherwise i Will Do in Next Version

Thanks

**Comment by sharmajatin1997** [comment]
@MohamedMahmoud10 Feature Added in New Version Please Check
